[ksk/kak] opens spotify after every new ksk start

diff --git a/ksk/kak b/ksk/kak
--- a/ksk/kak
+++ b/ksk/kak
@@ -3,9 +3,14 @@ clear
 SESSION_NAME="kiosk"
 
 while true; do
-  if ! tmux has-session -t "$SESSION_NAME" 2>/dev/null; then
-    echo "tmux session '$SESSION_NAME' not found. Running ksk..."
-    bash ~/scripts/ksk/ksk
-  fi
-  sleep 1
+    if ! pgrep -fx "spotify" >/dev/null; then
+        spotify >/dev/null 2>&1 &
+        sleep 3
+        xdotool key Alt+Tab
+    fi
+    if ! tmux has-session -t "$SESSION_NAME" 2>/dev/null; then
+        echo "tmux session '$SESSION_NAME' not found. Running ksk..."
+        bash ~/scripts/ksk/ksk
+    fi
+    sleep 1
 done
